#!/usr/bin/env python3
"""Generates firmware/src/aws_certs.h from this Terraform module's outputs
and local certs/ directory (see main.tf). Run manually after `terraform
apply` (or whenever the AWS IoT Thing/certs change) - this is not part of
the Docker build, since the firmware image only ever sees the generated
header, never AWS credentials or Terraform itself."""

import datetime
import json
import pathlib
import subprocess

SCRIPT_DIR = pathlib.Path(__file__).parent
CERTS_DIR = SCRIPT_DIR / "certs"
OUTPUT = SCRIPT_DIR.parent.parent.parent / "firmware" / "src" / "aws_certs.h"


def terraform_outputs():
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=SCRIPT_DIR, capture_output=True, text=True, check=True,
    )
    return json.loads(result.stdout)


def c_string_literal(text):
    """Render `text` as a C string literal: escape backslashes/quotes and
    turn real newlines into \\n escapes (one long line - fine for a
    generated header nobody hand-edits)."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def main():
    outputs = terraform_outputs()
    endpoint = outputs["iot_endpoint"]["value"]
    thing_name = outputs["thing_name"]["value"]
    mqtt_topic = outputs["mqtt_topic"]["value"]

    root_ca = (CERTS_DIR / "AmazonRootCA1.pem").read_text()
    device_cert = (CERTS_DIR / "device.pem.crt").read_text()
    device_key = (CERTS_DIR / "device.pem.key").read_text()

    OUTPUT.write_text(f"""\
/**
  ******************************************************************************
  * @file    aws_certs.h
  * @author  schoenenberger <rafael@schoenenberger.dev>
  * @date    {datetime.date.today().isoformat()}
  * @brief   AWS IoT endpoint/client/topic and the root CA/device cert/device
  *          key needed for the MQTT-over-TLS connection to AWS IoT Core -
  *          generated, do not edit by hand (see below)
  ******************************************************************************
  */

#ifndef AWS_CERTS_H
#define AWS_CERTS_H

/* Generated by infra/terraform/iot/generate_firmware_certs.py from
 * `terraform output` and certs/ - do not edit by hand, re-run the script
 * after `terraform apply` instead. */

#define AWS_IOT_ENDPOINT {c_string_literal(endpoint)}
#define AWS_IOT_CLIENT_ID {c_string_literal(thing_name)}
#define AWS_MQTT_TOPIC {c_string_literal(mqtt_topic)}

static const char AWS_ROOT_CA[] = {c_string_literal(root_ca)};
static const char AWS_DEVICE_CERT[] = {c_string_literal(device_cert)};
static const char AWS_DEVICE_KEY[] = {c_string_literal(device_key)};

#define AWS_ROOT_CA_LEN (sizeof(AWS_ROOT_CA) - 1)
#define AWS_DEVICE_CERT_LEN (sizeof(AWS_DEVICE_CERT) - 1)
#define AWS_DEVICE_KEY_LEN (sizeof(AWS_DEVICE_KEY) - 1)

#endif /* AWS_CERTS_H */
""")
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
