"""Generates firmware/src/aws_certs_key_params.h from this Terraform module's outputs
(see outputs.tf) and local certs/ directory (see main.tf). Run automatically
by run.ps1 after `terraform apply`, or manually whenever the AWS IoT
Thing/certs change. This is not part of the Docker build, since the
firmware image only ever sees the generated header, never AWS credentials
or Terraform itself"""

import datetime
import json
import os
import pathlib
import subprocess
import sys

SCRIPT_DIR = pathlib.Path(__file__).parent
CERTS_DIR = SCRIPT_DIR / "certs"
OUTPUT = SCRIPT_DIR.parent.parent.parent / "firmware" / "src" / "aws_certs_key_params.h"


def terraform_outputs():
    """Runs `terraform output -json`; shells out via the CLI since
    terraform.tfstate's JSON layout isn't a stable API, and provider.tf
    has a prepared (commented-out) S3 remote backend"""
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=SCRIPT_DIR, capture_output=True, text=True,
    )
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr, end="")
        sys.exit(result.returncode)
    return json.loads(result.stdout)


def main():
    """Reads the Terraform outputs and the 3 cert/key files from certs/,
    then writes them all into OUTPUT as a single generated C header"""
    outputs = terraform_outputs()
    endpoint = outputs["iot_endpoint"]["value"]
    thing_name = outputs["thing_name"]["value"]
    mqtt_topic = outputs["mqtt_topic"]["value"]

    root_ca = (CERTS_DIR / "AmazonRootCA1.pem").read_text()
    device_cert = (CERTS_DIR / "device.pem.crt").read_text()
    device_key = (CERTS_DIR / "device.pem.key").read_text()

    # json.dumps() below doubles as a C string literal generator (JSON
    # escaping is a superset of what C needs).
    OUTPUT.write_text(f"""\
/**
  ******************************************************************************
  * @file    aws_certs_key_params.h
  * @author  schoenenberger <rafael@schoenenberger.dev>
  * @date    {datetime.date.today().isoformat()}
  * @brief   AWS IoT endpoint/client/topic and the root CA/device cert/device
  *          key needed for the MQTT-over-TLS connection to AWS IoT Core;
  *          generated, do not edit by hand (see below)
  ******************************************************************************
  */

#ifndef AWS_CERTS_KEY_PARAMS_H
#define AWS_CERTS_KEY_PARAMS_H

/* Generated by infra/terraform/iot/generate_fw_certs_key_and_params.py from
 * `terraform output` and certs/; do not edit by hand, re-run the script
 * after `terraform apply` instead. */

#define AWS_IOT_ENDPOINT {json.dumps(endpoint)}
#define AWS_IOT_CLIENT_ID {json.dumps(thing_name)}
#define AWS_MQTT_TOPIC {json.dumps(mqtt_topic)}

static const char AWS_ROOT_CA[] = {json.dumps(root_ca)};
#define AWS_ROOT_CA_LEN (sizeof(AWS_ROOT_CA) - 1)

static const char AWS_DEVICE_CERT[] = {json.dumps(device_cert)};
#define AWS_DEVICE_CERT_LEN (sizeof(AWS_DEVICE_CERT) - 1)

static const char AWS_DEVICE_KEY[] = {json.dumps(device_key)};
#define AWS_DEVICE_KEY_LEN (sizeof(AWS_DEVICE_KEY) - 1)

#endif /* AWS_CERTS_KEY_PARAMS_H */
""")
    # 0o600 = read+write for the owner only, no access for anyone else.
    # No-op on Windows (no POSIX permission bits), but restricts the private
    # key on Linux/macOS; matches the certs_dir local_file resources' 0600.
    os.chmod(OUTPUT, 0o600)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
